project:
  type: website

website:
  # title: "topologicpy-tutorials"
  navbar:
    left:
      - href: index.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - Building_Tower.ipynb
      - EnergyModel.ipynb
      - MEP.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



