# TODO: setup auto-update pixi.lock https://pixi.sh/latest/advanced/updates_github_actions/#how-to-use

name: Build docs

on:
    push:
      branches: [add-pixi]
    pull_request:
      branches: [add-pixi]

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.2
        with:
            pixi-version: v0.63.2
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'add-pixi' }}
      - run: pixi run install-openstudio
      - run: pixi run tutorials
      - name: Push docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: tutorials/_site
